services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      Redis__ConnectionString: "redis:6379"
      Kafka__BootstrapServers: "kafka:9092"
      Kafka__ClickTopic: "url-clicked"
      Kafka__ConsumerGroup: "click-count-consumer"
      OpenTelemetry__Endpoint: "http://otel-collector:4317"
    depends_on:
      - postgres
      - redis
      - kafka

  postgres:
    image: postgres:18
    container_name: urlshortener-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: urlshortener-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: apache/kafka:4.3.1
    container_name: urlshortener-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: urlshortener-otel-collector
    restart: unless-stopped
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - ./src/UrlShortenerBackend/Observability/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: urlshortener-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: urlshortener-prometheus
    restart: unless-stopped
    volumes:
      - ./src/UrlShortenerBackend/Observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.1.1
    container_name: urlshortener-grafana
    restart: unless-stopped
    ports:
      - "3100:3000"
    depends_on:
      - prometheus
      - jaeger

volumes:
  postgres_data:
  redis_data:
  kafka_data:
