name: .NET CICD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10

      - name: Restore dependencies
        run: dotnet restore src/UrlShortenerBackend/UrlShortenerBackend.csproj

      - name: Build service
        run: dotnet build src/UrlShortenerBackend/UrlShortenerBackend.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test test/UrlShortenerBackendTests/UrlShortenerBackendTests.csproj --configuration Release --no-restore --verbosity normal

      - name: Build Docker image
        run: docker build -t urlshortener-api .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: urlshortener-api
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Log in to Amazon ECR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR image URI
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: ecr
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI="${ACCOUNT_ID}.dkr.ecr.eu-west-2.amazonaws.com/urlshortener-api"
          echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"

      - name: Tag Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker tag urlshortener-api \
            ${{ steps.ecr.outputs.image_uri }}:sha-${{ github.sha }}

      - name: Push Docker image to ECR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker push \
            ${{ steps.ecr.outputs.image_uri }}:sha-${{ github.sha }}
